services:
  german-bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: german-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=sqlite:///data/bot.db
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
      - POLLING_INTERVAL=${POLLING_INTERVAL:-1.0}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge