name: Dependency Updates

on:
  schedule:
    # Check for dependency updates daily at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install UV
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        
    - name: Update dependencies
      run: |
        # Update lockfile
        uv lock --upgrade
        
        # Check if there are any changes
        if git diff --quiet uv.lock; then
          echo "No dependency updates available"
          echo "updates_available=false" >> $GITHUB_ENV
        else
          echo "Dependency updates found"
          echo "updates_available=true" >> $GITHUB_ENV
        fi
        
    - name: Create Pull Request
      if: env.updates_available == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          🤖 Automated dependency updates
          
          This PR updates the project dependencies to their latest versions.
          
          ## Changes
          - Updated `uv.lock` with latest dependency versions
          
          ## Testing
          - [ ] Tests pass
          - [ ] Security scan passes
          - [ ] Docker build succeeds
          
          Auto-generated by GitHub Actions
        branch: chore/dependency-updates
        delete-branch: true
        draft: false